AWSTemplateFormatVersion: '2010-09-09'
Description: Stack to create Lambda functions

Resources:
  InterceptorSNSLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: InterceptorSNSFunction
      Runtime: python3.9
      Handler: interceptor_lambda.handler
      Code:
        S3Bucket: !ImportValue JournalEventBucketNameExport  # Importa el nombre del bucket desde el primer stack
        S3Key: interceptor-lambda-code-bucket/function1.zip
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 10

  ConnectorSFLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ConnectorSF
      Runtime: python3.9
      Handler: connector_sf_lambda.handler
      Code:
        S3Bucket: !ImportValue JournalEventBucketNameExport  # Importa el nombre del bucket desde el primer stack
        S3Key: connector-sf-lambda-code-bucket/function2.zip
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 10

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
