AWSTemplateFormatVersion: '2010-09-09'
Description: Stack to create an S3 bucket for Lambda code storage

Resources:
  JournalEventBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "journal-event-${AWS::AccountId}-${AWS::Region}"

Outputs:
  JournalEventBucketName:
    Description: S3 Bucket name for journal events
    Value: !Ref JournalEventBucket
